apiVersion: notification.halo.run/v1alpha1
kind: NotificationTemplate
metadata:
  name: template-new-comment-on-post
spec:
  reasonSelector:
    reasonType: new-comment-on-post
    language: default
  template:
    title: "[(${commenter})] 评论了你的文章《[(${postTitle})]》"
    rawBody: |
      [(${subscriber.displayName})] 你好：

        [(${commenter})] 评论了你的文章 《[(${postTitle})]》，以下是评论的具体内容：

        [(${content})]
    htmlBody: |
      <div style="
          border-radius: 10px 10px 10px 10px;
          font-size: 13px;
          color: #555555;
          width: 666px;
          margin: 50px auto;
          border: 1px solid #eee;
          max-width: 100%;
          background: #ffffff repeating-linear-gradient(-45deg,#fff,#fff 1.125rem,transparent 1.125rem,transparent 2.25rem);
          box-shadow: 0 1px 5px rgb(0 0 0 / 15%);">
          <div style="
          background:#49BDAD;
          color:#ffffff;
          border-radius: 10px 10px 0 0;
          background-image: -moz-linear-gradient(0deg, rgb(67, 198, 184), rgb(255, 209, 244));
          background-image: -webkit-linear-gradient(0deg, rgb(67, 198, 184), rgb(255, 209, 244));
          height: 66px;">
              <p style="font-size:15px;
              word-break:break-all;
              padding: 23px 32px;
              margin:0;
              background-color: hsla(0,0%,100%,.4);
              border-radius: 10px 10px 0 0;">
                  来自<a style="text-decoration:none;
                  color: #ffffff;" th:href="${site.url}" target="_blank" th:text="${site.title} + ' - ' + ${site.subtitle}"></a>的邮件
              </p>
          </div>
          <div style="margin:20px auto;
          width:90%">
              <div style="background: #fafafa repeating-linear-gradient(-45deg,#fff,#fff 1.125rem,transparent 1.125rem,transparent 2.25rem);
              box-shadow: 0 2px 5px rgba(0, 0, 0, 0.15);
              margin:20px 0;
              padding:15px;
              border-radius:5px;
              font-size:14px;">
                  <p>
                    <span th:text="${commenter}"></span> 评论了你的文章 
                    <a th:href="${postUrl}" target="_blank" th:text="|《${postTitle}》|"></a>
                    <span>，以下是评论的具体内容：</span>
                  </p>
                  <pre class="content" th:text="${content}" style="font-size: 16px; color: #333; background-color: #f9f9f9; padding: 10px; border-radius: 5px; white-space: pre-wrap;"></pre>
              </div>
              <div style="color: #8c8c8c; font-size: 10px;width: 100%;text-align: center;word-wrap: break-word;">
                  <p style="padding: 20px">我们，终将重逢。——《原神》</p>
              </div>
          </div>
      </div>


---
apiVersion: notification.halo.run/v1alpha1
kind: NotificationTemplate
metadata:
  name: template-new-comment-on-single-page
spec:
  reasonSelector:
    reasonType: new-comment-on-single-page
    language: default
  template:
    title: "[(${commenter})] 评论了你的页面《[(${pageTitle})]》"
    rawBody: |
      [(${subscriber.displayName})] 你好：

        [(${commenter})] 评论了你的页面 《[(${pageTitle})]》，以下是评论的具体内容：

        [(${content})]
    htmlBody: |
      <div style="
          border-radius: 10px 10px 10px 10px;
          font-size: 13px;
          color: #555555;
          width: 666px;
          margin: 50px auto;
          border: 1px solid #eee;
          max-width: 100%;
          background: #ffffff repeating-linear-gradient(-45deg,#fff,#fff 1.125rem,transparent 1.125rem,transparent 2.25rem);
          box-shadow: 0 1px 5px rgb(0 0 0 / 15%);">
          <div style="
          background:#49BDAD;
          color:#ffffff;
          border-radius: 10px 10px 0 0;
          background-image: -moz-linear-gradient(0deg, rgb(67, 198, 184), rgb(255, 209, 244));
          background-image: -webkit-linear-gradient(0deg, rgb(67, 198, 184), rgb(255, 209, 244));
          height: 66px;">
              <p style="font-size:15px;
              word-break:break-all;
              padding: 23px 32px;
              margin:0;
              background-color: hsla(0,0%,100%,.4);
              border-radius: 10px 10px 0 0;">
                  来自<a style="text-decoration:none;
                  color: #ffffff;" th:href="${site.url}" target="_blank" th:text="${site.title} + ' - ' + ${site.subtitle}"></a>的邮件
              </p>
          </div>
          <div style="margin:20px auto;
          width:90%">
              <div style="background: #fafafa repeating-linear-gradient(-45deg,#fff,#fff 1.125rem,transparent 1.125rem,transparent 2.25rem);
              box-shadow: 0 2px 5px rgba(0, 0, 0, 0.15);
              margin:20px 0;
              padding:15px;
              border-radius:5px;
              font-size:14px;">
                  <p>
                    <span th:text="${commenter}"></span> 评论了你的页面 
                    <a th:href="${pageUrl}" target="_blank" th:text="|《${pageTitle}》|"></a>
                    <span>，以下是评论的具体内容：</span>
                  </p>
                  <pre class="content" th:text="${content}" style="font-size: 16px; color: #333; background-color: #f9f9f9; padding: 10px; border-radius: 5px; white-space: pre-wrap;"></pre>
              </div>
              <div style="color: #8c8c8c; font-size: 10px;width: 100%;text-align: center;word-wrap: break-word;">
                  <p style="padding: 20px">我们，终将重逢。——《原神》</p>
              </div>
          </div>
      </div>


---
apiVersion: notification.halo.run/v1alpha1
kind: NotificationTemplate
metadata:
  name: template-someone-replied-to-you
spec:
  reasonSelector:
    reasonType: someone-replied-to-you
    language: default
  template:
    title: "[(${replier})] 在评论中回复了你"
    rawBody: |
      [(${subscriber.displayName})] 你好：

        [(${replier})] 在评论“[(${isQuoteReply ? quoteContent : commentContent})]”中回复了你，以下是回复的具体内容：

        [(${content})]
    htmlBody: |
      <div style="
          border-radius: 10px 10px 10px 10px;
          font-size: 13px;
          color: #555555;
          width: 666px;
          margin: 50px auto;
          border: 1px solid #eee;
          max-width: 100%;
          background: #ffffff repeating-linear-gradient(-45deg,#fff,#fff 1.125rem,transparent 1.125rem,transparent 2.25rem);
          box-shadow: 0 1px 5px rgb(0 0 0 / 15%);">
          <div style="
          background:#49BDAD;
          color:#ffffff;
          border-radius: 10px 10px 0 0;
          background-image: -moz-linear-gradient(0deg, rgb(67, 198, 184), rgb(255, 209, 244));
          background-image: -webkit-linear-gradient(0deg, rgb(67, 198, 184), rgb(255, 209, 244));
          height: 66px;">
              <p style="font-size:15px;
              word-break:break-all;
              padding: 23px 32px;
              margin:0;
              background-color: hsla(0,0%,100%,.4);
              border-radius: 10px 10px 0 0;">
                  来自<a style="text-decoration:none;
                  color: #ffffff;" th:href="${site.url}" target="_blank" th:text="${site.title} + ' - ' + ${site.subtitle}"></a>的邮件
              </p>
          </div>
          <div style="margin:20px auto;
          width:90%">
              <div style="background: #fafafa repeating-linear-gradient(-45deg,#fff,#fff 1.125rem,transparent 1.125rem,transparent 2.25rem);
              box-shadow: 0 2px 5px rgba(0, 0, 0, 0.15);
              margin:20px 0;
              padding:15px;
              border-radius:5px;
              font-size:14px;">
                  <p>
                    <span th:text="${replier}"></span> 在评论
                    <a th:href="${commentSubjectUrl}" target="_blank" th:text="|”${isQuoteReply ? quoteContent : commentContent}”|"></a>
                    <span>中回复了你，以下是回复的具体内容：</span>
                  </p>
                  <pre class="content" th:text="${content}" style="font-size: 16px; color: #333; background-color: #f9f9f9; padding: 10px; border-radius: 5px; white-space: pre-wrap;"></pre>
              </div>
              <div style="color: #8c8c8c; font-size: 10px;width: 100%;text-align: center;word-wrap: break-word;">
                  <p style="padding: 20px">我们，终将重逢。——《原神》</p>
              </div>
          </div>
      </div>

---
apiVersion: notification.halo.run/v1alpha1
kind: NotificationTemplate
metadata:
  name: template-email-verification
spec:
  reasonSelector:
    reasonType: email-verification
    language: default
  template:
    title: "邮箱验证-[(${site.title})]"
    rawBody: |
      【[(${site.title})]】你的邮箱验证码是：[(${code})]，请在 [(${expirationAtMinutes})] 分钟内完成验证。
    htmlBody: |
      <div style="
          border-radius: 10px;
          font-size: 13px;
          color: #555555;
          width: 666px;
          margin: 50px auto;
          border: 1px solid #eee;
          max-width: 100%;
          background: #ffffff repeating-linear-gradient(-45deg,#fff,#fff 1.125rem,transparent 1.125rem,transparent 2.25rem);
          box-shadow: 0 1px 5px rgb(0 0 0 / 15%);">
          <div style="
          background:#49BDAD;
          color:#ffffff;
          border-radius: 10px 10px 0 0;
          background-image: -moz-linear-gradient(0deg, rgb(67, 198, 184), rgb(255, 209, 244));
          background-image: -webkit-linear-gradient(0deg, rgb(67, 198, 184), rgb(255, 209, 244));
          height: 66px;">
              <p style="font-size:15px;
              word-break:break-all;
              padding: 23px 32px;
              margin:0;
              background-color: hsla(0,0%,100%,.4);
              border-radius: 10px 10px 0 0;">
                  来自<a style="text-decoration:none;
                  color: #ffffff;" th:href="${site.url}" target="_blank" th:text="${site.title} + ' - ' + ${site.subtitle}"></a>的邮件
              </p>
          </div>
          <div style="margin:20px auto;
          width:90%">
              <div style="background: #fafafa repeating-linear-gradient(-45deg,#fff,#fff 1.125rem,transparent 1.125rem,transparent 2.25rem);
              box-shadow: 0 2px 5px rgba(0, 0, 0, 0.15);
              margin:20px 0;
              padding:15px;
              border-radius:5px;
              font-size:14px;">
                  <p>使用下面的动态验证码（OTP）验证您的电子邮件地址。</p>
                  <div class="verify-code" style="font-size:24px;line-height:24px;color:#333;">
                    <b th:text="${code}"></b>
                  </div>
                  <p th:text="|动态验证码的有效期为 ${expirationAtMinutes} 分钟。|"></p>
                  <p>如果您没有尝试验证您的电子邮件地址，请忽略此电子邮件。</p>
              </div>
              <div style="color: #8c8c8c; font-size: 10px;width: 100%;text-align: center;word-wrap: break-word;">
                  <p style="padding: 20px">我们，终将重逢。——《原神》</p>
              </div>
          </div>
      </div>

---
apiVersion: notification.halo.run/v1alpha1
kind: NotificationTemplate
metadata:
  name: template-reset-password-by-email
spec:
  reasonSelector:
    reasonType: reset-password-by-email
    language: default
  template:
    title: "重置密码-[(${site.title})]"
    rawBody: |
      【[(${site.title})]】你已经请求了重置密码，可以链接来重置密码：[(${link})]，请在 [(${expirationAtMinutes})] 分钟内完成重置。
    htmlBody: |
      <div style="
          border-radius: 10px;
          font-size: 13px;
          color: #555555;
          width: 666px;
          margin: 50px auto;
          border: 1px solid #eee;
          max-width: 100%;
          background: #ffffff repeating-linear-gradient(-45deg,#fff,#fff 1.125rem,transparent 1.125rem,transparent 2.25rem);
          box-shadow: 0 1px 5px rgb(0 0 0 / 15%);">
          <div style="
          background:#49BDAD;
          color:#ffffff;
          border-radius: 10px 10px 0 0;
          background-image: -moz-linear-gradient(0deg, rgb(67, 198, 184), rgb(255, 209, 244));
          background-image: -webkit-linear-gradient(0deg, rgb(67, 198, 184), rgb(255, 209, 244));
          height: 66px;">
              <p style="font-size:15px;
              word-break:break-all;
              padding: 23px 32px;
              margin:0;
              background-color: hsla(0,0%,100%,.4);
              border-radius: 10px 10px 0 0;">
                  来自<a style="text-decoration:none;
                  color: #ffffff;" th:href="${site.url}" target="_blank" th:text="${site.title} + ' - ' + ${site.subtitle}"></a>的邮件
              </p>
          </div>
          <div style="margin:20px auto;
          width:90%">
              <div style="background: #fafafa repeating-linear-gradient(-45deg,#fff,#fff 1.125rem,transparent 1.125rem,transparent 2.25rem);
              box-shadow: 0 2px 5px rgba(0, 0, 0, 0.15);
              margin:20px 0;
              padding:15px;
              border-radius:5px;
              font-size:14px;">
                  <p>你已经请求了重置密码，可以点击下面的链接来重置密码：</p>
                  <div class="reset-link" style="line-height:24px;">
                    <span th:text="${link}"></span>
                  </div>
                  <p th:text="|链接有效期为 ${expirationAtMinutes} 分钟，请尽快完成重置。|"></p>
                  <p>如果您没有请求重置密码，请忽略此电子邮件。</p>
              </div>
              <div style="color: #8c8c8c; font-size: 10px;width: 100%;text-align: center;word-wrap: break-word;">
                  <p style="padding: 20px">我们，终将重逢。——《原神》</p>
              </div>
          </div>
      </div>

---
apiVersion: notification.halo.run/v1alpha1
kind: NotificationTemplate
metadata:
  name: template-new-device-login
spec:
  reasonSelector:
    reasonType: new-device-login
    language: default
  template:
    title: "你的 [(${site.title})] 账号被用于在 [(${os})] 上登录"
    rawBody: |
      [(${subscriber.displayName})] 你好：

        你的 [(${site.title})] 账号被用于在 [(${os})] 的 [(${browser})] 上登录。
        时间：[(${loginTime})]
        IP 地址：[(${ipAddress})] 
        如果你知悉上述信息，请忽略此电子邮件。
        如果你最近没有使用你的 Halo 账号登录并相信有人可能访问了你的账户，请尽快重设你的密码。
    htmlBody: |
      <div style="
          border-radius: 10px;
          font-size: 13px;
          color: #555555;
          width: 666px;
          margin: 50px auto;
          border: 1px solid #eee;
          max-width: 100%;
          background: #ffffff repeating-linear-gradient(-45deg,#fff,#fff 1.125rem,transparent 1.125rem,transparent 2.25rem);
          box-shadow: 0 1px 5px rgb(0 0 0 / 15%);">
          <div style="
          background:#49BDAD;
          color:#ffffff;
          border-radius: 10px 10px 0 0;
          background-image: -moz-linear-gradient(0deg, rgb(67, 198, 184), rgb(255, 209, 244));
          background-image: -webkit-linear-gradient(0deg, rgb(67, 198, 184), rgb(255, 209, 244));
          height: 66px;">
              <p style="font-size:15px;
              word-break:break-all;
              padding: 23px 32px;
              margin:0;
              background-color: hsla(0,0%,100%,.4);
              border-radius: 10px 10px 0 0;">
                  来自<a style="text-decoration:none;
                  color: #ffffff;" th:href="${site.url}" target="_blank" th:text="${site.title} + ' - ' + ${site.subtitle}"></a>的邮件
              </p>
          </div>
          <div style="margin:20px auto;
          width:90%">
              <div style="background: #fafafa repeating-linear-gradient(-45deg,#fff,#fff 1.125rem,transparent 1.125rem,transparent 2.25rem);
              box-shadow: 0 2px 5px rgba(0, 0, 0, 0.15);
              margin:20px 0;
              padding:15px;
              border-radius:5px;
              font-size:14px;">
                  <p th:text="|你的 ${site.title} 账号被用于在 ${os} 的 ${browser} 上登录：|"></p>
                  <div class="device-info">
                    <p th:text="|时间： ${loginTime}|"></p>
                    <p th:text="|IP 地址： ${ipAddress}|"></p>
                  </div>
                  <p>如果你知悉上述信息，请忽略此电子邮件。</p>
                  <p th:text="|如果你最近没有使用你的 ${site.title} 账号登录并相信有人可能访问了你的账户。|"></p>
                  <p th:text="|请务必对你的密码进行重设，以免造成损失。|"></p>
              </div>
              <div style="color: #8c8c8c; font-size: 10px;width: 100%;text-align: center;word-wrap: break-word;">
                  <p style="padding: 20px">我们，终将重逢。——《原神》</p>
              </div>
          </div>
      </div>
